//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime version: :4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapCore.Tests.WsdlFromFile.Services
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	[System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.w3.org/2002/ws/databinding/examples/6/09/", ConfigurationName = "IncludePortType")]
	public interface IncludePortType
	{

		[System.ServiceModel.OperationContractAttribute(Action = "http://www.w3.org/2002/ws/databinding/examples/6/09/#echoInclude", ReplyAction = "*")]
		[System.ServiceModel.XmlSerializerFormatAttribute()]
		echoIncludeResponse echoInclude(echoIncludeRequest request);

		// CODEGEN: Generating message contract because the operation has multiple return values.
		[System.ServiceModel.OperationContractAttribute(Action = "http://www.w3.org/2002/ws/databinding/examples/6/09/#echoInclude", ReplyAction = "*")]
		System.Threading.Tasks.Task<echoIncludeResponse> echoIncludeAsync(echoIncludeRequest request);
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.w3.org/2002/ws/databinding/examples/6/09/")]
	public partial class echoInclude
	{

		private string includeField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string include
		{
			get
			{
				return this.includeField;
			}
			set
			{
				this.includeField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
	public partial class echoIncludeRequest
	{

		[System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.w3.org/2002/ws/databinding/examples/6/09/", Order = 0)]
		public echoInclude echoInclude;

		public echoIncludeRequest()
		{
		}

		public echoIncludeRequest(echoInclude echoInclude)
		{
			this.echoInclude = echoInclude;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
	public partial class echoIncludeResponse
	{

		[System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.w3.org/2002/ws/databinding/examples/6/09/", Order = 0)]
		public echoInclude echoInclude;

		public echoIncludeResponse()
		{
		}

		public echoIncludeResponse(echoInclude echoInclude)
		{
			this.echoInclude = echoInclude;
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	public interface IncludePortTypeChannel : IncludePortType, System.ServiceModel.IClientChannel
	{
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	public partial class IncludePortTypeClient : System.ServiceModel.ClientBase<IncludePortType>, IncludePortType
	{

		public IncludePortTypeClient()
		{
		}

		public IncludePortTypeClient(string endpointConfigurationName) :
				base(endpointConfigurationName)
		{
		}

		public IncludePortTypeClient(string endpointConfigurationName, string remoteAddress) :
				base(endpointConfigurationName, remoteAddress)
		{
		}

		public IncludePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
				base(endpointConfigurationName, remoteAddress)
		{
		}

		public IncludePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
				base(binding, remoteAddress)
		{
		}

		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
		echoIncludeResponse IncludePortType.echoInclude(echoIncludeRequest request)
		{
			return base.Channel.echoInclude(request);
		}

		public echoInclude echoInclude(echoInclude echoInclude1)
		{
			echoIncludeRequest inValue = new echoIncludeRequest();
			inValue.echoInclude = echoInclude1;
			echoIncludeResponse retVal = ((IncludePortType)(this)).echoInclude(inValue);
			return retVal.echoInclude;
		}

		public System.Threading.Tasks.Task<echoIncludeResponse> echoIncludeAsync(echoIncludeRequest request)
		{
			return base.Channel.echoIncludeAsync(request);
		}
	}

}
