//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapCore.Tests.WsdlFromFile.Services
{
	using DatexII = SoapCore.Tests.WsdlFromFile.Services;


	[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://datex2.eu/wsdl/snapshotPull/2020", ConfigurationName="DatexII.snapshotPullInterface")]
    public interface snapshotPullInterface
    {
        
        // CODEGEN: Generating message contract since the operation pullSnapshotData is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://datex2.eu/wsdl/snapshotPull/2020/pullData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LocationReference))]
        DatexII.pullSnapshotDataResponse pullSnapshotData(DatexII.pullSnapshotDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://datex2.eu/wsdl/snapshotPull/2020/pullData", ReplyAction="*")]
        System.Threading.Tasks.Task<DatexII.pullSnapshotDataResponse> pullSnapshotDataAsync(DatexII.pullSnapshotDataRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/messageContainer")]
    public partial class MessageContainer
    {
        
        private PayloadPublication[] payloadField;
        
        private ExchangeInformation exchangeInformationField;
        
        private _ExtensionType _messageContainerExtensionField;
        
        private string modelBaseVersionField;
        
        private string extensionNameField;
        
        private string extensionVersionField;
        
        private string profileNameField;
        
        private string profileVersionField;
        
        public MessageContainer()
        {
            this.modelBaseVersionField = "3";
            this.extensionNameField = "Exchange 2018";
            this.extensionVersionField = "1";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("payload", Order=0)]
        public PayloadPublication[] payload
        {
            get
            {
                return this.payloadField;
            }
            set
            {
                this.payloadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ExchangeInformation exchangeInformation
        {
            get
            {
                return this.exchangeInformationField;
            }
            set
            {
                this.exchangeInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public _ExtensionType _messageContainerExtension
        {
            get
            {
                return this._messageContainerExtensionField;
            }
            set
            {
                this._messageContainerExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string modelBaseVersion
        {
            get
            {
                return this.modelBaseVersionField;
            }
            set
            {
                this.modelBaseVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Exchange 2018")]
        public string extensionName
        {
            get
            {
                return this.extensionNameField;
            }
            set
            {
                this.extensionNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("1")]
        public string extensionVersion
        {
            get
            {
                return this.extensionVersionField;
            }
            set
            {
                this.extensionVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string profileName
        {
            get
            {
                return this.profileNameField;
            }
            set
            {
                this.profileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string profileVersion
        {
            get
            {
                return this.profileVersionField;
            }
            set
            {
                this.profileVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PredefinedLocationsPublication))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/common")]
    public abstract partial class PayloadPublication
    {
        
        private string feedTypeField;
        
        private System.DateTime publicationTimeField;
        
        private InternationalIdentifier publicationCreatorField;
        
        private _ExtensionType _payloadPublicationExtensionField;
        
        private string langField;
        
        private string modelBaseVersionField;
        
        private string extensionNameField;
        
        private string extensionVersionField;
        
        private string profileNameField;
        
        private string profileVersionField;
        
        public PayloadPublication()
        {
            this.modelBaseVersionField = "3";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string feedType
        {
            get
            {
                return this.feedTypeField;
            }
            set
            {
                this.feedTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime publicationTime
        {
            get
            {
                return this.publicationTimeField;
            }
            set
            {
                this.publicationTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public InternationalIdentifier publicationCreator
        {
            get
            {
                return this.publicationCreatorField;
            }
            set
            {
                this.publicationCreatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public _ExtensionType _payloadPublicationExtension
        {
            get
            {
                return this._payloadPublicationExtensionField;
            }
            set
            {
                this._payloadPublicationExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string modelBaseVersion
        {
            get
            {
                return this.modelBaseVersionField;
            }
            set
            {
                this.modelBaseVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string extensionName
        {
            get
            {
                return this.extensionNameField;
            }
            set
            {
                this.extensionNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string extensionVersion
        {
            get
            {
                return this.extensionVersionField;
            }
            set
            {
                this.extensionVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string profileName
        {
            get
            {
                return this.profileNameField;
            }
            set
            {
                this.profileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string profileVersion
        {
            get
            {
                return this.profileVersionField;
            }
            set
            {
                this.profileVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/common")]
    public partial class InternationalIdentifier
    {
        
        private string countryField;
        
        private string nationalIdentifierField;
        
        private _ExtensionType _internationalIdentifierExtensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string nationalIdentifier
        {
            get
            {
                return this.nationalIdentifierField;
            }
            set
            {
                this.nationalIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public _ExtensionType _internationalIdentifierExtension
        {
            get
            {
                return this._internationalIdentifierExtensionField;
            }
            set
            {
                this._internationalIdentifierExtensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/common")]
    public partial class _ExtensionType
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/exchangeInformation")]
    public partial class _ExchangeReturnEnum
    {
        
        private string _extendedValueField;
        
        private ExchangeReturnEnum valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string _extendedValue
        {
            get
            {
                return this._extendedValueField;
            }
            set
            {
                this._extendedValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public ExchangeReturnEnum Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/exchangeInformation")]
    public enum ExchangeReturnEnum
    {
        
        /// <remarks/>
        fail,
        
        /// <remarks/>
        _extended,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/exchangeInformation")]
    public partial class ReturnInformation
    {
        
        private _ExchangeReturnEnum returnStatusField;
        
        private MultilingualString returnStatusReasonField;
        
        private _ExtensionType _returnInformationExtensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public _ExchangeReturnEnum returnStatus
        {
            get
            {
                return this.returnStatusField;
            }
            set
            {
                this.returnStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MultilingualString returnStatusReason
        {
            get
            {
                return this.returnStatusReasonField;
            }
            set
            {
                this.returnStatusReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public _ExtensionType _returnInformationExtension
        {
            get
            {
                return this._returnInformationExtensionField;
            }
            set
            {
                this._returnInformationExtensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/common")]
    public partial class MultilingualString
    {
        
        private MultilingualStringValue[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("value", IsNullable=false)]
        public MultilingualStringValue[] values
        {
            get
            {
                return this.valuesField;
            }
            set
            {
                this.valuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/common")]
    public partial class MultilingualStringValue
    {
        
        private string langField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/exchangeInformation")]
    public partial class _ExchangeStatusEnum
    {
        
        private string _extendedValueField;
        
        private ExchangeStatusEnum valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string _extendedValue
        {
            get
            {
                return this._extendedValueField;
            }
            set
            {
                this._extendedValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public ExchangeStatusEnum Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/exchangeInformation")]
    public enum ExchangeStatusEnum
    {
        
        /// <remarks/>
        undefined,
        
        /// <remarks/>
        _extended,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/exchangeInformation")]
    public partial class DynamicInformation
    {
        
        private _ExchangeStatusEnum exchangeStatusField;
        
        private System.DateTime messageGenerationTimestampField;
        
        private ReturnInformation returnInformationField;
        
        private _ExtensionType _dynamicInformationExtensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public _ExchangeStatusEnum exchangeStatus
        {
            get
            {
                return this.exchangeStatusField;
            }
            set
            {
                this.exchangeStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime messageGenerationTimestamp
        {
            get
            {
                return this.messageGenerationTimestampField;
            }
            set
            {
                this.messageGenerationTimestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ReturnInformation returnInformation
        {
            get
            {
                return this.returnInformationField;
            }
            set
            {
                this.returnInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public _ExtensionType _dynamicInformationExtension
        {
            get
            {
                return this._dynamicInformationExtensionField;
            }
            set
            {
                this._dynamicInformationExtensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/exchangeInformation")]
    public partial class Agent
    {
        
        private InternationalIdentifier internationalIdentifierField;
        
        private _ExtensionType _agentExtensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public InternationalIdentifier internationalIdentifier
        {
            get
            {
                return this.internationalIdentifierField;
            }
            set
            {
                this.internationalIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public _ExtensionType _agentExtension
        {
            get
            {
                return this._agentExtensionField;
            }
            set
            {
                this._agentExtensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/exchangeInformation")]
    public partial class _ProtocolTypeEnum
    {
        
        private string _extendedValueField;
        
        private ProtocolTypeEnum valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string _extendedValue
        {
            get
            {
                return this._extendedValueField;
            }
            set
            {
                this._extendedValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public ProtocolTypeEnum Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/exchangeInformation")]
    public enum ProtocolTypeEnum
    {
        
        /// <remarks/>
        snapshotPull,
        
        /// <remarks/>
        _extended,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/exchangeInformation")]
    public partial class ExchangeContext
    {
        
        private _ProtocolTypeEnum codedExchangeProtocolField;
        
        private string exchangeSpecificationVersionField;
        
        private Agent supplierOrCisRequesterField;
        
        private _ExtensionType _exchangeContextExtensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public _ProtocolTypeEnum codedExchangeProtocol
        {
            get
            {
                return this.codedExchangeProtocolField;
            }
            set
            {
                this.codedExchangeProtocolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string exchangeSpecificationVersion
        {
            get
            {
                return this.exchangeSpecificationVersionField;
            }
            set
            {
                this.exchangeSpecificationVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Agent supplierOrCisRequester
        {
            get
            {
                return this.supplierOrCisRequesterField;
            }
            set
            {
                this.supplierOrCisRequesterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public _ExtensionType _exchangeContextExtension
        {
            get
            {
                return this._exchangeContextExtensionField;
            }
            set
            {
                this._exchangeContextExtensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/exchangeInformation")]
    public partial class _MessageTypeEnum
    {
        
        private string _extendedValueField;
        
        private MessageTypeEnum valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string _extendedValue
        {
            get
            {
                return this._extendedValueField;
            }
            set
            {
                this._extendedValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public MessageTypeEnum Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/exchangeInformation")]
    public enum MessageTypeEnum
    {
        
        /// <remarks/>
        payloadDelivery,
        
        /// <remarks/>
        openSession,
        
        /// <remarks/>
        keepAlive,
        
        /// <remarks/>
        closeSession,
        
        /// <remarks/>
        @return,
        
        /// <remarks/>
        CISServiceRequest,
        
        /// <remarks/>
        CISFeedback,
        
        /// <remarks/>
        _extended,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/exchangeInformation")]
    public partial class ExchangeInformation
    {
        
        private _MessageTypeEnum messageTypeField;
        
        private ExchangeContext exchangeContextField;
        
        private DynamicInformation dynamicInformationField;
        
        private _ExtensionType _exchangeInformationExtensionField;
        
        private string modelBaseVersionField;
        
        private string extensionNameField;
        
        private string extensionVersionField;
        
        private string profileNameField;
        
        private string profileVersionField;
        
        public ExchangeInformation()
        {
            this.modelBaseVersionField = "3";
            this.extensionNameField = "Exchange 2018";
            this.extensionVersionField = "1";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public _MessageTypeEnum messageType
        {
            get
            {
                return this.messageTypeField;
            }
            set
            {
                this.messageTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ExchangeContext exchangeContext
        {
            get
            {
                return this.exchangeContextField;
            }
            set
            {
                this.exchangeContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public DynamicInformation dynamicInformation
        {
            get
            {
                return this.dynamicInformationField;
            }
            set
            {
                this.dynamicInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public _ExtensionType _exchangeInformationExtension
        {
            get
            {
                return this._exchangeInformationExtensionField;
            }
            set
            {
                this._exchangeInformationExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string modelBaseVersion
        {
            get
            {
                return this.modelBaseVersionField;
            }
            set
            {
                this.modelBaseVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Exchange 2018")]
        public string extensionName
        {
            get
            {
                return this.extensionNameField;
            }
            set
            {
                this.extensionNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("1")]
        public string extensionVersion
        {
            get
            {
                return this.extensionVersionField;
            }
            set
            {
                this.extensionVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string profileName
        {
            get
            {
                return this.profileNameField;
            }
            set
            {
                this.profileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string profileVersion
        {
            get
            {
                return this.profileVersionField;
            }
            set
            {
                this.profileVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GmlLinearRing))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/locationReferencing")]
    public partial class GmlLineString
    {
        
        private string posListField;
        
        private _ExtensionType _gmlLineStringExtensionField;
        
        private string srsDimensionField;
        
        private string srsNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string posList
        {
            get
            {
                return this.posListField;
            }
            set
            {
                this.posListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public _ExtensionType _gmlLineStringExtension
        {
            get
            {
                return this._gmlLineStringExtensionField;
            }
            set
            {
                this._gmlLineStringExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string srsDimension
        {
            get
            {
                return this.srsDimensionField;
            }
            set
            {
                this.srsDimensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string srsName
        {
            get
            {
                return this.srsNameField;
            }
            set
            {
                this.srsNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/locationReferencing")]
    public partial class GmlLinearRing : GmlLineString
    {
        
        private _ExtensionType _gmlLinearRingExtensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public _ExtensionType _gmlLinearRingExtension
        {
            get
            {
                return this._gmlLinearRingExtensionField;
            }
            set
            {
                this._gmlLinearRingExtensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/locationReferencing")]
    public partial class RoadInformation
    {
        
        private string roadNameField;
        
        private string roadNumberField;
        
        private _ExtensionType _roadInformationExtensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string roadName
        {
            get
            {
                return this.roadNameField;
            }
            set
            {
                this.roadNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string roadNumber
        {
            get
            {
                return this.roadNumberField;
            }
            set
            {
                this.roadNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public _ExtensionType _roadInformationExtension
        {
            get
            {
                return this._roadInformationExtensionField;
            }
            set
            {
                this._roadInformationExtensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/locationReferencing")]
    public partial class SupplementaryPositionalDescription
    {
        
        private MultilingualString locationDescriptionField;
        
        private RoadInformation[] roadInformationField;
        
        private _ExtensionType _supplementaryPositionalDescriptionExtensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MultilingualString locationDescription
        {
            get
            {
                return this.locationDescriptionField;
            }
            set
            {
                this.locationDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("roadInformation", Order=1)]
        public RoadInformation[] roadInformation
        {
            get
            {
                return this.roadInformationField;
            }
            set
            {
                this.roadInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public _ExtensionType _supplementaryPositionalDescriptionExtension
        {
            get
            {
                return this._supplementaryPositionalDescriptionExtensionField;
            }
            set
            {
                this._supplementaryPositionalDescriptionExtensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/locationReferencing")]
    public partial class _HeightTypeEnum
    {
        
        private string _extendedValueField;
        
        private HeightTypeEnum valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string _extendedValue
        {
            get
            {
                return this._extendedValueField;
            }
            set
            {
                this._extendedValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public HeightTypeEnum Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/locationReferencing")]
    public enum HeightTypeEnum
    {
        
        /// <remarks/>
        ellipsoidalHeight,
        
        /// <remarks/>
        gravityRelatedHeight,
        
        /// <remarks/>
        relativeHeight,
        
        /// <remarks/>
        _extended,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/locationReferencing")]
    public partial class HeightCoordinate
    {
        
        private float heightValueField;
        
        private _HeightTypeEnum heightTypeField;
        
        private _ExtensionType _heightCoordinateExtensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public float heightValue
        {
            get
            {
                return this.heightValueField;
            }
            set
            {
                this.heightValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public _HeightTypeEnum heightType
        {
            get
            {
                return this.heightTypeField;
            }
            set
            {
                this.heightTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public _ExtensionType _heightCoordinateExtension
        {
            get
            {
                return this._heightCoordinateExtensionField;
            }
            set
            {
                this._heightCoordinateExtensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/locationReferencing")]
    public partial class PointCoordinates
    {
        
        private float latitudeField;
        
        private float longitudeField;
        
        private HeightCoordinate[] heightCoordinateField;
        
        private _ExtensionType _pointCoordinatesExtensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public float latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public float longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("heightCoordinate", Order=2)]
        public HeightCoordinate[] heightCoordinate
        {
            get
            {
                return this.heightCoordinateField;
            }
            set
            {
                this.heightCoordinateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public _ExtensionType _pointCoordinatesExtension
        {
            get
            {
                return this._pointCoordinatesExtensionField;
            }
            set
            {
                this._pointCoordinatesExtensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LocationGroup))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LocationGroupByList))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Location))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NetworkLocation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LinearLocation))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/locationReferencing")]
    public abstract partial class LocationReference
    {
        
        private _ExtensionType _locationReferenceExtensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public _ExtensionType _locationReferenceExtension
        {
            get
            {
                return this._locationReferenceExtensionField;
            }
            set
            {
                this._locationReferenceExtensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LocationGroupByList))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/locationReferencing")]
    public abstract partial class LocationGroup : LocationReference
    {
        
        private _ExtensionType _locationGroupExtensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public _ExtensionType _locationGroupExtension
        {
            get
            {
                return this._locationGroupExtensionField;
            }
            set
            {
                this._locationGroupExtensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/locationReferencing")]
    public partial class LocationGroupByList : LocationGroup
    {
        
        private Location[] locationContainedInGroupField;
        
        private _ExtensionType _locationGroupByListExtensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("locationContainedInGroup", Order=0)]
        public Location[] locationContainedInGroup
        {
            get
            {
                return this.locationContainedInGroupField;
            }
            set
            {
                this.locationContainedInGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public _ExtensionType _locationGroupByListExtension
        {
            get
            {
                return this._locationGroupByListExtensionField;
            }
            set
            {
                this._locationGroupByListExtensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NetworkLocation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LinearLocation))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/locationReferencing")]
    public abstract partial class Location : LocationReference
    {
        
        private PointCoordinates coordinatesForDisplayField;
        
        private _ExtensionType _locationExtensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PointCoordinates coordinatesForDisplay
        {
            get
            {
                return this.coordinatesForDisplayField;
            }
            set
            {
                this.coordinatesForDisplayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public _ExtensionType _locationExtension
        {
            get
            {
                return this._locationExtensionField;
            }
            set
            {
                this._locationExtensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LinearLocation))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/locationReferencing")]
    public abstract partial class NetworkLocation : Location
    {
        
        private SupplementaryPositionalDescription supplementaryPositionalDescriptionField;
        
        private _ExtensionType _networkLocationExtensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SupplementaryPositionalDescription supplementaryPositionalDescription
        {
            get
            {
                return this.supplementaryPositionalDescriptionField;
            }
            set
            {
                this.supplementaryPositionalDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public _ExtensionType _networkLocationExtension
        {
            get
            {
                return this._networkLocationExtensionField;
            }
            set
            {
                this._networkLocationExtensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/locationReferencing")]
    public partial class LinearLocation : NetworkLocation
    {
        
        private GmlLineString gmlLineStringField;
        
        private _ExtensionType _linearLocationExtensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public GmlLineString gmlLineString
        {
            get
            {
                return this.gmlLineStringField;
            }
            set
            {
                this.gmlLineStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public _ExtensionType _linearLocationExtension
        {
            get
            {
                return this._linearLocationExtensionField;
            }
            set
            {
                this._linearLocationExtensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PredefinedLocationGroup))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/locationReferencing")]
    public abstract partial class PredefinedLocationReference
    {
        
        private _ExtensionType _predefinedLocationReferenceExtensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public _ExtensionType _predefinedLocationReferenceExtension
        {
            get
            {
                return this._predefinedLocationReferenceExtensionField;
            }
            set
            {
                this._predefinedLocationReferenceExtensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/locationReferencing")]
    public partial class PredefinedLocationGroup : PredefinedLocationReference
    {
        
        private MultilingualString predefinedLocationGroupNameField;
        
        private LocationGroup locationGroupField;
        
        private _ExtensionType _predefinedLocationGroupExtensionField;
        
        private string idField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MultilingualString predefinedLocationGroupName
        {
            get
            {
                return this.predefinedLocationGroupNameField;
            }
            set
            {
                this.predefinedLocationGroupNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public LocationGroup locationGroup
        {
            get
            {
                return this.locationGroupField;
            }
            set
            {
                this.locationGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public _ExtensionType _predefinedLocationGroupExtension
        {
            get
            {
                return this._predefinedLocationGroupExtensionField;
            }
            set
            {
                this._predefinedLocationGroupExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/common")]
    public partial class _InformationStatusEnum
    {
        
        private string _extendedValueField;
        
        private InformationStatusEnum valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string _extendedValue
        {
            get
            {
                return this._extendedValueField;
            }
            set
            {
                this._extendedValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public InformationStatusEnum Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/common")]
    public enum InformationStatusEnum
    {
        
        /// <remarks/>
        real,
        
        /// <remarks/>
        securityExercise,
        
        /// <remarks/>
        technicalExercise,
        
        /// <remarks/>
        test,
        
        /// <remarks/>
        _extended,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/common")]
    public partial class HeaderInformation
    {
        
        private _InformationStatusEnum informationStatusField;
        
        private _ExtensionType _headerInformationExtensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public _InformationStatusEnum informationStatus
        {
            get
            {
                return this.informationStatusField;
            }
            set
            {
                this.informationStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public _ExtensionType _headerInformationExtension
        {
            get
            {
                return this._headerInformationExtensionField;
            }
            set
            {
                this._headerInformationExtensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datex2.eu/schema/3/locationReferencing")]
    public partial class PredefinedLocationsPublication : PayloadPublication
    {
        
        private HeaderInformation headerInformationField;
        
        private PredefinedLocationReference[] predefinedLocationReferenceField;
        
        private _ExtensionType _predefinedLocationsPublicationExtensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public HeaderInformation headerInformation
        {
            get
            {
                return this.headerInformationField;
            }
            set
            {
                this.headerInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("predefinedLocationReference", Order=1)]
        public PredefinedLocationReference[] predefinedLocationReference
        {
            get
            {
                return this.predefinedLocationReferenceField;
            }
            set
            {
                this.predefinedLocationReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public _ExtensionType _predefinedLocationsPublicationExtension
        {
            get
            {
                return this._predefinedLocationsPublicationExtensionField;
            }
            set
            {
                this._predefinedLocationsPublicationExtensionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pullSnapshotDataRequest
    {
        
        public pullSnapshotDataRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pullSnapshotDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://datex2.eu/wsdl/snapshotPull/2020", Order=0)]
        public DatexII.MessageContainer pullSnapshotDataOutput;
        
        public pullSnapshotDataResponse()
        {
        }
        
        public pullSnapshotDataResponse(DatexII.MessageContainer pullSnapshotDataOutput)
        {
            this.pullSnapshotDataOutput = pullSnapshotDataOutput;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface snapshotPullInterfaceChannel : DatexII.snapshotPullInterface, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class snapshotPullInterfaceClient : System.ServiceModel.ClientBase<DatexII.snapshotPullInterface>, DatexII.snapshotPullInterface
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public snapshotPullInterfaceClient() : 
                base(snapshotPullInterfaceClient.GetDefaultBinding(), snapshotPullInterfaceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.snapshotPullSoapEndPoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public snapshotPullInterfaceClient(EndpointConfiguration endpointConfiguration) : 
                base(snapshotPullInterfaceClient.GetBindingForEndpoint(endpointConfiguration), snapshotPullInterfaceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public snapshotPullInterfaceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(snapshotPullInterfaceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public snapshotPullInterfaceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(snapshotPullInterfaceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public snapshotPullInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DatexII.pullSnapshotDataResponse DatexII.snapshotPullInterface.pullSnapshotData(DatexII.pullSnapshotDataRequest request)
        {
            return base.Channel.pullSnapshotData(request);
        }
        
        public DatexII.MessageContainer pullSnapshotData()
        {
            DatexII.pullSnapshotDataRequest inValue = new DatexII.pullSnapshotDataRequest();
            DatexII.pullSnapshotDataResponse retVal = ((DatexII.snapshotPullInterface)(this)).pullSnapshotData(inValue);
            return retVal.pullSnapshotDataOutput;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DatexII.pullSnapshotDataResponse> DatexII.snapshotPullInterface.pullSnapshotDataAsync(DatexII.pullSnapshotDataRequest request)
        {
            return base.Channel.pullSnapshotDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<DatexII.pullSnapshotDataResponse> pullSnapshotDataAsync()
        {
            DatexII.pullSnapshotDataRequest inValue = new DatexII.pullSnapshotDataRequest();
            return ((DatexII.snapshotPullInterface)(this)).pullSnapshotDataAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.snapshotPullSoapEndPoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.snapshotPullSoapEndPoint))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/snapshotPullService/2020");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return snapshotPullInterfaceClient.GetBindingForEndpoint(EndpointConfiguration.snapshotPullSoapEndPoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return snapshotPullInterfaceClient.GetEndpointAddress(EndpointConfiguration.snapshotPullSoapEndPoint);
        }
        
        public enum EndpointConfiguration
        {
            
            snapshotPullSoapEndPoint,
        }
    }
}
