name: CI

on: [push, pull_request, pull_request_review]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker://alpine
    steps:
      - uses: actions/checkout@v4
      - name: prepare deps
        run: apk add bash icu-libs krb5-libs libgcc libintl libssl3 libstdc++ zlib curl
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            3.1.x
            8.0.x
      - name: build && test
        run: dotnet test src/SoapCore.Tests
